# fly.toml app configuration file generated for restorebyeric on 2023-08-16T03:40:02+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restorebyeric"
primary_region = "sin"

[build]
  image = "etee96/restore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51NeD0fIKmViXhXhgMTdku0GFuBpFsZ32jdaMamEaw05mhO4U8xY79oQSsksDiJmROZjEZbow151ZFRUHOKjEegRc00YzDSv0m6"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
